Book.id=123
Book.title=Who is issue here
Book.price=23423
Book.authors=Rajjo,Rajat,Rani

Student.sid=23
Student.sname=Gaurav
Student.course=java

Course.courseId=123
Course.courseName=Java
Course.courseCost=456